{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"VentasActuales\",\"Prueba\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.144.1378.0 (25.06)+cba1e61f16ea36d44901f06fa446299040122394"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "75c0319e-aa58-422c-88e8-9e66ca491ef1",
        "fromColumn": "Fecha Alta",
        "fromTable": "VentasActuales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_59d766fa-26be-410e-ab32-15a3eda2519d"
      },
      {
        "name": "a28b00a9-7d9d-4946-bd9c-f83f6eac93b3",
        "fromColumn": "Fecha Venta",
        "fromTable": "VentasActuales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3109d731-0dc7-4aad-b18f-7b5e1d70cf72"
      }
    ],
    "sourceQueryCulture": "es-CO",
    "tables": [
      {
        "name": "VentasActuales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Ref",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "881f3c76-cc06-403e-90ca-417442c649e1",
            "sourceColumn": "Ref",
            "summarizeBy": "sum"
          },
          {
            "name": "Fecha Alta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c5d993b1-02ce-478e-8540-3e2e12ed6f22",
            "sourceColumn": "Fecha Alta",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_59d766fa-26be-410e-ab32-15a3eda2519d"
                },
                "isDefault": true,
                "relationship": "75c0319e-aa58-422c-88e8-9e66ca491ef1"
              }
            ]
          },
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15645c14-e304-4541-8fd2-2d00c757a120",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          },
          {
            "name": "OP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80b6d6d0-386b-4adc-8340-f064909d60d4",
            "sourceColumn": "OP",
            "summarizeBy": "none"
          },
          {
            "name": "Superficie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "18e3fb61-8c1b-4f64-9849-86daa3c58425",
            "sourceColumn": "Superficie",
            "summarizeBy": "sum"
          },
          {
            "name": "Venta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d3500ca7-b310-483e-bc26-9ab522fcfeea",
            "sourceColumn": "Venta",
            "summarizeBy": "sum"
          },
          {
            "name": "Fecha Venta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "886a9e52-2e20-41ac-b1e7-eb2a860a3eb0",
            "sourceColumn": "Fecha Venta",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_3109d731-0dc7-4aad-b18f-7b5e1d70cf72"
                },
                "isDefault": true,
                "relationship": "a28b00a9-7d9d-4946-bd9c-f83f6eac93b3"
              }
            ]
          },
          {
            "name": "Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "995c9365-61b8-415f-b5d9-8c7b7f29fd73",
            "sourceColumn": "Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Provincia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98dbebca-db5a-4735-916b-be48d3e41cc4",
            "sourceColumn": "Provincia",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cd8879ee-9c19-4704-978d-ab813d31e078",
        "measures": [
          {
            "name": "Color barras",
            "expression": "IF(SUM(VentasActuales[Venta])>705000000,\"Red\",\"Black\")",
            "lineageTag": "2162b7da-974a-4901-a969-dadb598dd929"
          },
          {
            "name": "Título de Ventas",
            "expression": "\"Total de ventas por el Tipo \"& SELECTEDVALUE(VentasActuales[Tipo])& \" es: \"& FORMAT(SUM(VentasActuales[Venta]),\"$00,00.00\")",
            "lineageTag": "b617ea67-6f33-40cd-b840-872a38a49de1"
          }
        ],
        "partitions": [
          {
            "name": "VentasActuales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://cmconsultingsas-my.sharepoint.com/personal/ronald_ramos_cmconsulting_com_co/Documents/Documents/BD-Inmuebles.xlsx\"), null, true),",
                "    VentasActuales_Table = Source{[Item=\"VentasActuales\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(VentasActuales_Table,{{\"Ref\", Int64.Type}, {\"Fecha Alta\", type date}, {\"Tipo\", type text}, {\"OP\", type text}, {\"Provincia\", type text}, {\"Superficie\", Int64.Type}, {\"Venta\", type number}, {\"Fecha Venta\", type date}, {\"Vendedor\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_02b4b1ce-fc49-42eb-8b60-1cb243b71204",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ac83e420-dba0-4cb6-b037-fcd107519f12",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2994b11d-dce0-422a-86ea-ecdab56f3041",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e31e04ae-8718-43af-ad88-ccc4ca1451f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5ec744a2-2073-4af2-982e-d10897855f60",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c9e7a699-c679-4596-ada9-61d3e0c77ae9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "0c46dd3c-a088-41e1-a990-3e9b88e92f60",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "ff211f14-ed1e-4c05-95c5-f3d79ceb3842",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "ce24f26d-7506-474b-b216-a5d800e53413",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "4e8cf0af-d8fa-4bb7-a0f7-40fa84f1f0af",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "5c644fbe-4a88-472b-b9c5-de4cd91cebe1",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "80643b96-6557-48d9-aca7-8b02441fee05",
                "ordinal": 3
              }
            ],
            "lineageTag": "8674ecd5-b660-433e-b681-4b7e4c2b7d01"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "69c2542f-c15f-4e7b-bfc4-c2b83a0caa42",
        "partitions": [
          {
            "name": "DateTableTemplate_02b4b1ce-fc49-42eb-8b60-1cb243b71204",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_59d766fa-26be-410e-ab32-15a3eda2519d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f6bfb728-7a4f-4c63-ab76-72e6254c4f8a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d43b90ad-dbf1-4540-a27a-78b6e9c55616",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ac5b467e-896a-4588-9e17-9391c191b7f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bbaaf11c-9a6d-4745-8e0f-fae54ea1aa26",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "f05be865-feb8-4485-aa39-74d286a7eb26",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "7bc30046-4f4f-4b67-86da-d7bde66ee075",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "34ae752a-ca22-4cb6-a0be-8964ba662a60",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "c84a8f63-33b1-47f5-bc6b-de94d8b9fe8d",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "8569f7ce-ef54-4b62-b25c-e6df1d423570",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "36424249-827f-4192-a6ad-e16d3d85cd6e",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "3ceb94dc-d745-4efe-b69f-445fe20b12ba",
                "ordinal": 3
              }
            ],
            "lineageTag": "9f9ba758-7a2f-4aad-bbf1-b65ae51d7125"
          }
        ],
        "isHidden": true,
        "lineageTag": "b66f0890-2189-4048-b2cb-3df554985dfc",
        "partitions": [
          {
            "name": "LocalDateTable_59d766fa-26be-410e-ab32-15a3eda2519d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VentasActuales'[Fecha Alta])), 1, 1), Date(Year(MAX('VentasActuales'[Fecha Alta])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_3109d731-0dc7-4aad-b18f-7b5e1d70cf72",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "531af84e-4775-4c52-b16d-5f036cf9526c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "172fb6c5-bf75-4eeb-ac8b-a3cfcb2a9c66",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8510de23-79b0-441f-9912-ff320a415d8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6e03115c-0165-4c59-9969-8b4f4727068b",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "eb924083-0bca-4842-b4d4-1c4e818125ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "61987d26-de8e-497b-9ef9-5faa1578827a",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "bda95c1b-c48d-4c40-9421-e3619678ac22",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "12b50f43-c8b7-4205-958f-6828ae257d4d",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "3cf122a4-f39f-41cd-95f5-16e568db6648",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "e810bf02-3e7e-452f-8c82-cd2a9741833a",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "ad41e599-7080-4f10-b0b0-4b42befd8494",
                "ordinal": 3
              }
            ],
            "lineageTag": "d4404240-8964-4c7d-aba0-9bd28e305d4e"
          }
        ],
        "isHidden": true,
        "lineageTag": "e30cd1e0-07f7-4bac-bc86-330acba976db",
        "partitions": [
          {
            "name": "LocalDateTable_3109d731-0dc7-4aad-b18f-7b5e1d70cf72",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VentasActuales'[Fecha Venta])), 1, 1), Date(Year(MAX('VentasActuales'[Fecha Venta])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Prueba",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de59c71b-4e3e-422b-8f72-3bb7aec244c5",
            "sourceColumn": "1",
            "summarizeBy": "none"
          },
          {
            "name": "2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4b04277-b89d-4060-957a-8adece6e90b6",
            "sourceColumn": "2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a759fc1f-bd3d-4232-8209-67e3286c1557",
        "partitions": [
          {
            "name": "Prueba",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WKk5JLE5R0lFKBNOxsQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"1\" = _t, #\"2\" = _t]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"1\", type text}, {\"2\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}